version: '3'
services:
  # CLIENT
  client_dans_backend:
    container_name: client_dans_backend
    restart: always
    env_file:
      - ./client/.env.local
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server_dans_backend
    ports:
      - "3000:3000"
    links:
      - server_dans_backend:server_dans_backend
    entrypoint: /client/entrypoint.sh


  # SERVER
  server_dans_backend:
    container_name: server_dans_backend
    build:
      context: .  # declaring the current (root) dir as the context so we can access "Pipfile"
      dockerfile: server/Dockerfile
    env_file:  # setting env file for local development
      - ./server/.env
    depends_on:
      - db_dans_backend
    ports:
      - "8000:8000"
    links:
      - db_dans_backend:db_dans_backend
    entrypoint: /app/server/entrypoint.sh


  # DATABASE
  db_dans_backend:
    container_name: db_dans_backend
    restart: always
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=dans_backend
      - POSTGRES_USER=dans_backend
      - POSTGRES_PASSWORD=dans_backend
      - POSTGRES_HOST=db_dans_backend
    ports:
      - "5432:5432"


  # NGINX SERVER
  nginx_dans_backend:
    container_name: nginx_dans_backend
    build:
      context: nginx/default
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - server_dans_backend
      - client_dans_backend

